// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ErrorsSample.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ErrorsSample {
  public static partial class SqrtService
  {
    static readonly string __ServiceName = "ErrorsSample.SqrtService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::ErrorsSample.SqrtRequest> __Marshaller_ErrorsSample_SqrtRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ErrorsSample.SqrtRequest.Parser));
    static readonly grpc::Marshaller<global::ErrorsSample.SqrtResponse> __Marshaller_ErrorsSample_SqrtResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ErrorsSample.SqrtResponse.Parser));

    static readonly grpc::Method<global::ErrorsSample.SqrtRequest, global::ErrorsSample.SqrtResponse> __Method_Sqrt = new grpc::Method<global::ErrorsSample.SqrtRequest, global::ErrorsSample.SqrtResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Sqrt",
        __Marshaller_ErrorsSample_SqrtRequest,
        __Marshaller_ErrorsSample_SqrtResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ErrorsSample.ErrorsSampleReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for SqrtService</summary>
    public partial class SqrtServiceClient : grpc::ClientBase<SqrtServiceClient>
    {
      /// <summary>Creates a new client for SqrtService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SqrtServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SqrtService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SqrtServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SqrtServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SqrtServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::ErrorsSample.SqrtResponse Sqrt(global::ErrorsSample.SqrtRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Sqrt(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ErrorsSample.SqrtResponse Sqrt(global::ErrorsSample.SqrtRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Sqrt, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ErrorsSample.SqrtResponse> SqrtAsync(global::ErrorsSample.SqrtRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SqrtAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ErrorsSample.SqrtResponse> SqrtAsync(global::ErrorsSample.SqrtRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Sqrt, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SqrtServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SqrtServiceClient(configuration);
      }
    }

  }
}
#endregion
