// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PrimeNumber.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace PrimeNumber {
  public static partial class PrimeNumberDecompositionService
  {
    static readonly string __ServiceName = "PrimeNumber.PrimeNumberDecompositionService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::PrimeNumber.DecompositionRequest> __Marshaller_PrimeNumber_DecompositionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PrimeNumber.DecompositionRequest.Parser));
    static readonly grpc::Marshaller<global::PrimeNumber.DecompositionResponse> __Marshaller_PrimeNumber_DecompositionResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PrimeNumber.DecompositionResponse.Parser));

    static readonly grpc::Method<global::PrimeNumber.DecompositionRequest, global::PrimeNumber.DecompositionResponse> __Method_Decompose = new grpc::Method<global::PrimeNumber.DecompositionRequest, global::PrimeNumber.DecompositionResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Decompose",
        __Marshaller_PrimeNumber_DecompositionRequest,
        __Marshaller_PrimeNumber_DecompositionResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PrimeNumber.PrimeNumberReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for PrimeNumberDecompositionService</summary>
    public partial class PrimeNumberDecompositionServiceClient : grpc::ClientBase<PrimeNumberDecompositionServiceClient>
    {
      /// <summary>Creates a new client for PrimeNumberDecompositionService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PrimeNumberDecompositionServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PrimeNumberDecompositionService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PrimeNumberDecompositionServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PrimeNumberDecompositionServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PrimeNumberDecompositionServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::PrimeNumber.DecompositionResponse> Decompose(global::PrimeNumber.DecompositionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Decompose(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::PrimeNumber.DecompositionResponse> Decompose(global::PrimeNumber.DecompositionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Decompose, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PrimeNumberDecompositionServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PrimeNumberDecompositionServiceClient(configuration);
      }
    }

  }
}
#endregion
